import { Settings } from "./../components/Settings";
import { BackToSelectButton } from "./../components/BackToSelectButton";
import { SelectStratergy } from "./../components/SelectStratergy";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import useStratergy from "../hooks/useStratergy";
import { EtherInput } from "../components/EtherInput/EtherInput";
import TokensReadyToBuy from "../components/TokensReadyToBuy";
import { BuyTokens } from "../components/BuyTokens";
import { SettingsButton } from "../components/SettingsButton";
import Logo from "../components/Logo";
import useTokens from "../hooks/useTokens";

const Home: NextPage = () => {
  const [stratergy, setStratergy] = useState("");
  const [tokensLength, setTokensLength] = useState(10);
  const [slippage, setSlippage] = useState(10);
  const [stratResult, loading] = useStratergy(stratergy);
  const [tokens, setTokens] = useTokens(stratergy, stratResult, tokensLength);
  const [amountETHIn, setAmountETHIn] = useState(null);
  const [settingsActive, setSettingsActive] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Token Eater</title>
        <meta name="description" content="Generated by @rainbow-me/create-rainbowkit" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <ConnectButton />
      </header>
      <main className={styles.main}>
        {" "}
        <h1 className={styles.title}>
          {" "}
          <Logo />
        </h1>
        <div className={styles.card}>
          {stratergy && (
            <>
              {" "}
              {!settingsActive && (
                <>
                  <div className={styles.cardHeader}>
                    <BackToSelectButton setStratergy={setStratergy} />
                    <SettingsButton setSettingsActive={setSettingsActive} />
                  </div>
                  <EtherInput amountETHIn={amountETHIn} setAmountETHIn={setAmountETHIn} />
                  <BuyTokens tokens={tokens} loading={loading} amountETHIn={amountETHIn} />
                  <TokensReadyToBuy tokens={tokens} loading={loading} setTokens={setTokens} />
                </>
              )}
              {settingsActive && <Settings setSettingsActive={setSettingsActive} tokensLength={tokensLength} setTokensLength={setTokensLength} slippage={slippage} setSlippage={setSlippage} />}
            </>
          )}
          {!stratergy && (
            <>
              <SelectStratergy stratergy={stratergy} setStratergy={setStratergy} />
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
