import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import EtherAmount from "../components/EtherInput/EtherAmount";
import { SwapperCard } from "../components/SwapperCard";
import useArbitrumSubgraph from "../hooks/subgraph/useArbitrumSubgraph";
import useStratergy from "../hooks/useStratergy";

const Home: NextPage = () => {
  const [stratergy, setStratergy] = useState("Randomly Selected");
  const [tokens, setTokens] = useState([]);
  const [result, loading] = useStratergy(stratergy);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta name="description" content="Generated by @rainbow-me/create-rainbowkit" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <ConnectButton />
      </header>
      <main className={styles.main}>
        {" "}
        <h1 className={styles.title}>Token Eater</h1>
        <SwapperCard tokens={tokens} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
