import { Settings } from "./../components/Settings";
import { BackToSelectButton } from "./../components/BackToSelectButton";
import { SelectStratergy } from "./../components/SelectStratergy";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import EtherAmount from "../components/EtherInput/EtherAmount";
import useStratergy from "../hooks/useStratergy";
import { EtherInput } from "../components/EtherInput/EtherInput";
import TokensReadyToBuy from "../components/TokensReadyToBuy";
import { FormControl, InputLabel, Select, MenuItem } from "@mui/material";
import { BuyTokens } from "../components/BuyTokens";
import { SelectTokenListLength } from "../components/SelectTokenListLength";
import { SettingsButton } from "../components/SettingsButton";
import { BackToTokenList } from "../components/BackToTokenList";

const Home: NextPage = () => {
  const [stratergy, setStratergy] = useState("");
  const [poolsLength, setPoolsLength] = useState(10);
  const [pools, loading, setPools] = useStratergy(stratergy, poolsLength);
  const [amountETHIn, setAmountETHIn] = useState(null);
  const [settingsActive, setSettingsActive] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Token Eater</title>
        <meta name="description" content="Generated by @rainbow-me/create-rainbowkit" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <ConnectButton />
      </header>
      <main className={styles.main}>
        {" "}
        <h1 className={styles.title}>Token Eater</h1>
        <div className={styles.card}>
          {stratergy && (
            <>
              {" "}
              {!settingsActive && (
                <>
                  <div className={styles.cardHeader}>
                    <BackToSelectButton setStratergy={setStratergy} />
                    <SettingsButton setSettingsActive={setSettingsActive} />
                  </div>
                  <EtherInput amountETHIn={amountETHIn} setAmountETHIn={setAmountETHIn} />
                  <BuyTokens pools={pools} loading={loading} amountETHIn={amountETHIn} />
                  <TokensReadyToBuy pools={pools} loading={loading} setPools={setPools} />
                </>
              )}
              {settingsActive && <Settings setSettingsActive={setSettingsActive} />}
            </>
          )}
          {!stratergy && (
            <>
              <SelectStratergy setStratergy={setStratergy} />
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
