import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Logo from "../components/Logo";
import Crown from "../components/leaderboard/Crown";
import { Users } from "../components/leaderboard/Users";
import useLeaderboard from "../hooks/leaderboard/useLeaderboard";

const LeaderBoard: NextPage = () => {
  const [users, loading] = useLeaderboard();
  return (
    <div className={styles.container}>
      <Head>
        <title>Token Eater</title>
        <meta name="description" content="Generated by @rainbow-me/create-rainbowkit" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <ConnectButton />
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <Crown />
        </h1>
        <div className={styles.card}>
          <Users users={users} loading={loading} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default LeaderBoard;
